### ISSUE TITLE
Video Quality Improvement in Example 1

### ISSUE THREAD

**Issue by niteshgarg** [fyhertz/libstreaming-examples#24]
Hi There,

I was trying to implement example 1 and found that I am not able to control the video quality and as soon as I add below code to change the quality the app stops working. 

mSession.setVideoQuality(new VideoQuality(width, height, framerate,bitrate));

Is something can be done for this. 

Thanks,
Nitesh

**Comment by niteshgarg** [comment]
Sorry.. Its working.. I was making a mistake.

**Comment by ghost** [comment]
Hi Nitesh,
Can you please elaborate here, how did you exactly resolve it.
I am using the below code, and video quality is too poor.
mSession = SessionBuilder.getInstance()
                .setContext(getApplicationContext())
                .setAudioEncoder(SessionBuilder.AUDIO_AAC)
                .setAudioQuality(new AudioQuality(8000, 16000))  
                .setVideoEncoder(SessionBuilder.VIDEO_H264)
                //.setVideoQuality(new VideoQuality(352, 288, 15, 500*1024))
                .setVideoQuality(new VideoQuality(176,144,20,500000))
                .setCamera(CameraInfo.CAMERA_FACING_BACK)
                .setSurfaceView(mSurfaceView).setPreviewOrientation(90)
                .setCallback(this).build();

**Comment by niteshgarg** [comment]
```
                                                                                  Hi Karan,It's pretty simple. Just change the parameters passed to setVideoQuality method to 640,360 or whatever. Possible resolutions are looged when you start the app. Please refer those.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Karan BalkarSent: Sunday, 6 December 2015 16:35To: fyhertz/libstreaming-examplesReply To: fyhertz/libstreaming-examplesCc: niteshgargSubject: Re: [libstreaming-examples] Video Quality Improvement in Example 1 (#24)Hi Nitesh,
```

Can you please elaborate here, how did you exactly resolve it.
I am using the below code, and video quality is too poor.
mSession = SessionBuilder.getInstance()
                .setContext(getApplicationContext())
                .setAudioEncoder(SessionBuilder.AUDIO_AAC)
                .setAudioQuality(new AudioQuality(8000, 16000))
                .setVideoEncoder(SessionBuilder.VIDEO_H264)
                //.setVideoQuality(new VideoQuality(352, 288, 15, 500*1024))
                .setVideoQuality(new VideoQuality(176,144,20,500000))
                .setCamera(CameraInfo.CAMERA_FACING_BACK)
                .setSurfaceView(mSurfaceView).setPreviewOrientation(90)
                .setCallback(this).build();

—Reply to this email directly or view it on GitHub.

**Comment by ghost** [comment]
Hi Nitesh,

I tried the same but I am getting an exception saying "ConfNotSupportedException". I tried with .setVideoQuality(new VideoQuality(640,360,20,500000)) but still it did not work.

I am testing on Moto G
