### ISSUE TITLE
Example:1 blackscreen 

### ISSUE THREAD

**Issue by khyatiChitroda** [fyhertz/libstreaming-examples#49]
I have implemented example1, but nothing happen after installing it service has been start but to server created only black screen shows on mobile. please help me.

**Comment by khutes** [comment]
Hey how did you fix this issue? I am having the same problem

**Comment by khutes** [comment]
Nevermind, I found my mistake. The preview will not show until a client connects to the server. This was my reference: https://github.com/fyhertz/libstreaming/issues/161
